(function(){
'use strict';
const F=LabFeatures,M=LabModels,B=LabBacktest,L=LabBlind,$=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
let data=F.validate(JSON.parse($('lab-data').textContent)),cfg=M.config(),report=B.walkForward(data,cfg),state=L.empty(),legacyRows=[],ready=false,busy=false,mode='historical',page=0,selectedNumber=17,rankingSnapshot=null;
const pct=v=>v===null||v===undefined?'—':(v*100).toFixed(1)+'%',dec=v=>v===null||v===undefined?'—':v.toFixed(3),signed=v=>v===null?'—':(v>=0?'+':'')+v.toFixed(3),pad=n=>String(n).padStart(2,'0');
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function message(text){$('app-message').textContent=text}
function download(name,value,type='application/json'){const content=typeof value==='string'?value:JSON.stringify(value,null,2),url=URL.createObjectURL(new Blob([content],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function numbers(list,actual=[]){const box=el('div',undefined,'numbers');for(const n of list)box.append(el('span',pad(n),actual.includes(n)?'hit':''));return box}
function pool(){return Number($('pool').value)}function model(){return $('selected-model').value}
function source(){return mode==='live'?L.liveRows(state,$('live-config').value||'none'):report}
function filtered(ignoreMonth=false){return source().filter(r=>r.historyCount>=Number($('warmup').value)&&(ignoreMonth||$('month').value==='all'||r.date.startsWith($('month').value)))}
function emptyRow(target,cols,text='尚無可評估紀錄。'){const tr=el('tr'),td=el('td',text,'empty');td.colSpan=cols;tr.append(td);$(target).append(tr)}
function syncOptions(){const selected=$('month').value,months=[...new Set(source().map(r=>r.date.slice(0,7)))].sort();$('month').replaceChildren(new Option('全部月份','all'),...months.map(m=>new Option(m,m)));$('month').value=months.includes(selected)?selected:'all';const current=$('live-config').value,configs=[...new Set(state.seals.map(s=>s.configId))];$('live-config').replaceChildren(...(configs.length?configs.map(id=>new Option(id,id)):[new Option('尚無封存','none')]));$('live-config').value=configs.includes(current)?current:configs.at(-1)||'none'}
function renderMetrics(){const rows=filtered(),n=pool(),id=model(),s=B.stats(rows,id,n),rng=B.stats(rows,'G',n),leaders=B.compare(rows,n),ci=B.wilson(s.distribution.slice(3).reduce((a,b)=>a+b,0),s.count);$('kpi-average').textContent=dec(s.average);$('kpi-average-note').textContent='Top'+n+' · 理論 '+dec(B.theory(n).average);$('kpi-coverage').textContent=pct(s.coverage);$('kpi-rate').textContent=pct(s.rates[3]);$('kpi-interval').textContent=ci?'95%區間 '+pct(ci[0])+'–'+pct(ci[1]):'等待評估';$('kpi-delta').textContent=signed(s.count?s.average-rng.average:null);$('kpi-uplift').textContent=rng.average>0?'平均命中相對RNG '+((s.average/rng.average-1)*100).toFixed(1)+'%':'與同期間G平均命中相比';$('kpi-rank').textContent=s.count?'#'+(leaders.findIndex(m=>m.id===id)+1)+' / 7':'—';$('kpi-model').textContent=M.MODELS.find(m=>m.id===id).name;$('kpi-size').textContent=s.count;$('kpi-config').textContent=mode==='live'?$('live-config').value:M.configId(cfg);$('leader-label').textContent='Top'+n+' · Avg Hit排序';$('leaderboard').replaceChildren();for(let i=0;i<leaders.length;i++){const r=leaders[i],tr=el('tr',undefined,r.id===id?'selected':'');const name=el('td'),button=el('button',undefined,'model-button');button.type='button';button.append(el('span',s.count?'#'+(i+1):'—','rank-badge'),el('span',r.id+' · '+r.name),el('small',r.detail));button.addEventListener('click',()=>{$('selected-model').value=r.id;page=0;render()});name.append(button);tr.append(name,el('td',dec(r.average)),...([2,3,4,5].map(k=>el('td',pct(r.rates[k])))),el('td',pct(r.top15)),el('td',r.uplift===null?'—':(r.uplift>=0?'+':'')+r.uplift.toFixed(1)+'%',r.delta>0?'positive':r.delta<0?'negative':''),el('td',r.count));$('leaderboard').append(tr)}
$('coverage-bars').replaceChildren();$('coverage-table').replaceChildren();for(const p of B.POOLS){const a=B.stats(rows,id,p),g=B.stats(rows,'G',p),t=B.theory(p);const row=el('div',undefined,'pool-row'),track=el('div',undefined,'track'),fill=el('span');fill.style.width=(a.coverage||0)*100+'%';track.append(fill);row.append(el('span','Top'+p),track,el('span',pct(a.coverage)));$('coverage-bars').append(row);const tr=el('tr');['Top'+p,dec(a.average),pct(a.rates[3]),pct(g.rates[3]),pct(t.atLeast(3))].forEach(v=>tr.append(el('td',v)));$('coverage-table').append(tr)}renderStages(rows,id);renderMonthly();renderDetails();}
function renderStages(rows,id){$('stages').replaceChildren();for(const [i,n,goal] of [[1,20,.55],[2,15,.35],[3,10,.15]]){const s=B.stats(rows,id,n),t=B.theory(n).atLeast(3),section=el('div',undefined,'stage'),head=el('div',undefined,'section-head');head.append(el('strong','Stage '+i+' · Top'+n+' ≥3 > '+pct(goal)),el('span',s.count?(s.rates[3]>goal?'門檻達成':'尚未達成'):'等待資料',s.count&&s.rates[3]>goal?'status positive':'status neutral'));section.append(head,el('small','模型 '+pct(s.rates[3])+' · 理論隨機 '+pct(t)+' · 差 '+(s.count?((s.rates[3]-t)*100).toFixed(1)+'百分點':'—')));$('stages').append(section)}const s=el('div',undefined,'stage');s.append(el('strong','Stage 4 · Top5 ≥3 長期穩定高於RNG'),el('small','尚未證實。需固定設定版本累積前瞻資料，單次排行不判定達標。'));$('stages').append(s)}
function renderMonthly(){$('monthly').replaceChildren();const rows=filtered(true),months=[...new Set(rows.map(r=>r.date.slice(0,7)))].sort();for(const m of months){const subset=rows.filter(r=>r.date.startsWith(m)),s=B.stats(subset,model(),pool()),rng=B.stats(subset,'G',pool()),tr=el('tr');[m,s.count,dec(s.average),pct(s.rates[3]),signed(s.average-rng.average),s.win,s.tie,s.loss].forEach((v,i)=>tr.append(el('td',v,i===5?'positive':i===6?'neutral':i===7?'negative':'')));$('monthly').append(tr)}if(!months.length)emptyRow('monthly',8)}
function renderDetails(){const rows=[...filtered()].reverse(),max=Math.max(0,Math.ceil(rows.length/25)-1);page=Math.min(page,max);$('details').replaceChildren();for(const r of rows.slice(page*25,page*25+25)){const tr=el('tr'),name=el('td');name.append(el('div',r.period),el('small',r.date));const p=el('td'),a=el('td');p.append(numbers(r.models[model()].ranking.slice(0,pool()).map(x=>x.number),r.actual));a.append(numbers(r.actual));tr.append(name,p,a,el('td',r.models[model()].pools[pool()]+' / 5'),el('td',(r.trainingEnd||'無')+'（'+r.historyCount+'期）'));$('details').append(tr)}if(!rows.length)emptyRow('details',5);$('detail-count').textContent=rows.length+'期 · 每頁25期 · 綠色為命中';$('page-label').textContent=(page+1)+' / '+(max+1);$('prev-page').disabled=page===0;$('next-page').disabled=page===max;}
function renderRanking(){if(mode==='settings')return;const current=$('ranking-period').value;let options;if(mode==='live'){options=state.seals.filter(s=>s.configId===$('live-config').value).map(s=>new Option(s.period+' · 已封存',s.period))}else options=[new Option('下一期 · 尚未封存','next'),...data.map(r=>new Option(r.period+' / '+r.date,r.period)).reverse()];$('ranking-period').replaceChildren(...options);if(options.some(o=>o.value===current))$('ranking-period').value=current;const selected=$('ranking-period').value;let prediction;
if(mode==='live'){const s=state.seals.find(s=>s.period===selected);if(!s){$('ranking').replaceChildren();emptyRow('ranking',13);$('ranking-caption').textContent='尚無此設定的封存排名。';$('contribution').replaceChildren();return}prediction=M.predictions(s.training,s.period,s.config);$('ranking-caption').textContent=s.period+' · 封存設定 '+s.configId+' · 資料截至 '+s.training.at(-1).period}else{const index=selected==='next'?data.length:data.findIndex(r=>r.period===selected);const past=data.slice(0,index),period=selected==='next'?String(Number(data.at(-1).period)+1):selected;prediction=M.predictions(past,period,cfg);$('ranking-caption').textContent=period+' · '+(selected==='next'?'研究預覽，尚未封存':'回測時點重建')+' · 僅使用前 '+past.length+' 期'}
rankingSnapshot=prediction;$('ranking').replaceChildren();prediction.rankings[model()].forEach((item,i)=>{const raw=prediction.features.raw[item.number-1],tr=el('tr',undefined,item.number===selectedNumber?'selected':'');const cell=el('td'),button=el('button',pad(item.number),'model-button');button.type='button';button.setAttribute('aria-label','檢視'+item.number+'號模型貢獻');button.addEventListener('click',()=>{selectedNumber=item.number;renderRanking()});cell.append(button);tr.append(el('td',i+1),cell,el('td',item.score.toFixed(4)),el('td',raw.count10),el('td',raw.count30),el('td',raw.count100),el('td',(raw.missingCensored?'≥':'')+raw.missing),el('td',raw.trend.toFixed(3)),el('td',raw.co.toFixed(3)),el('td',raw.repeat?'是':'否'),el('td',raw.odd?'奇':'偶'),el('td',raw.small?'小':'大'),el('td',['1–13','14–26','27–39'][raw.zone-1]));$('ranking').append(tr)});renderContributions()}
function renderContributions(){const p=rankingSnapshot,total=Object.values(p.config.ensemble).reduce((a,b)=>a+b,0),box=$('contribution');box.replaceChildren(el('strong',pad(selectedNumber)+'號 · Ensemble拆解'));for(const id of ['A','B','C','D','E']){const score=p.rankings[id].find(x=>x.number===selectedNumber).score,weight=p.config.ensemble[id];box.append(el('span',id+': '+score.toFixed(3)+' × '+weight+' / '+total.toFixed(2)+' = '+(score*weight/total).toFixed(4)))}box.append(el('strong','總分 '+p.rankings.F.find(x=>x.number===selectedNumber).score.toFixed(4)))}
function renderBlind(){const p=L.pending(state);$('seal-button').disabled=!ready||busy||!!p;$('result-button').disabled=!ready||busy||!p;$('blind-date').disabled=!!p;$('blind-result').disabled=!p;$('export-blind').disabled=!ready||!state.seals.length;try{const history=L.historyWithResults(data,state);$('blind-period').value=String(Number(history.at(-1).period)+1)}catch(e){$('seal-button').disabled=true;message(e.message)}if(p)$('blind-period').value=p.period;$('blind-config-note').textContent='使用設定 '+M.configId(cfg)+' · '+M.VERSION;$('pending-label').textContent=p?'待評分 '+p.period+' · '+new Date(p.drawAt).toLocaleString():'尚無待評分期別。先封存，開獎後再登錄。';$('blind-list').replaceChildren();for(const s of [...state.seals].reverse()){const result=state.results.find(r=>r.sealHash===s.hash),box=el('div',undefined,'seal-card');box.append(el('h3',s.period+' · '+s.configId+' · '+(result?'已評分':'已封存，等待開獎')),el('div','封存 '+new Date(s.createdAt).toLocaleString()+' / 預定 '+new Date(s.drawAt).toLocaleString(),'muted'),el('div','SHA-256 '+s.hash,'hash'));if(result)box.append(numbers(result.actual));const details=el('details');details.append(el('summary','查看A–G封存的Top20（完整39碼可匯出）'));for(const m of M.MODELS){details.append(el('h3',m.id+' · '+m.name),numbers(s.rankings[m.id].slice(0,20).map(x=>x.number),result?.actual||[]))}box.append(details);$('blind-list').append(box)}if(!state.seals.length)$('blind-list').append(el('p','尚無Model Lab封存；歷史回測不計入前瞻成績。','muted'));}
function render(){for(const button of document.querySelectorAll('[data-tab]')){const active=button.dataset.tab===mode;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))}$('settings-panel').hidden=mode!=='settings';$('evaluation-panel').hidden=mode==='settings';$('ranking-panel').hidden=mode==='settings';$('blind-panel').hidden=mode!=='live';$('import-wrap').hidden=mode!=='historical';$('live-config-wrap').hidden=mode!=='live';$('data-range').textContent=data[0].date+' — '+data.at(-1).date+' · '+data.length+'期歷史資料 · 7模型 / 5種候選池';$('mode-notice').textContent=mode==='historical'?'歷史答案已查閱，此區用於開發比較。每期排名僅使用之前資料；調權重後的排行仍屬探索性回測。':'只統計已封存且已登錄答案的前瞻紀錄，依封存設定分組；修改目前權重不會重算原排名。';if(mode!=='settings'){renderMetrics();renderRanking()}renderBlind()}
function fillWeights(){for(const [group,target] of [['features','feature-weights'],['ensemble','ensemble-weights']]){$(target).replaceChildren();for(const key of Object.keys(cfg[group])){const box=el('div'),label=el('label',group==='features'?F.LABELS[key]:key+' · '+M.MODELS.find(m=>m.id===key).name),input=el('input');input.id='weight-'+group+'-'+key;label.htmlFor=input.id;input.type='number';input.min='0';input.max='10';input.step='0.05';input.required=true;input.value=cfg[group][key];box.append(label,input);$(target).append(box)}}}
for(const m of M.MODELS)$('selected-model').append(new Option(m.id+' · '+m.name,m.id));$('selected-model').value='F';for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>{mode=button.dataset.tab;page=0;syncOptions();render()});for(const id of ['pool','selected-model','month','warmup'])$(id).addEventListener('change',()=>{page=0;render()});$('ranking-period').addEventListener('change',renderRanking);$('live-config').addEventListener('change',()=>{page=0;syncOptions();render()});$('prev-page').addEventListener('click',()=>{page--;renderDetails()});$('next-page').addEventListener('click',()=>{page++;renderDetails()});$('goto-blind').addEventListener('click',()=>{mode='live';page=0;syncOptions();render();$('blind-panel').scrollIntoView({behavior:'smooth',block:'start'})});
$('weights-form').addEventListener('submit',e=>{e.preventDefault();try{const next={features:{},ensemble:{}};for(const group of Object.keys(next))for(const key of Object.keys(cfg[group]))next[group][key]=Number($('weight-'+group+'-'+key).value);const settings=M.config(next),computed=B.walkForward(data,settings);cfg=settings;report=computed;page=0;render();message('已套用 '+M.configId(cfg)+'。這是新的探索設定，尚未驗證；封存紀錄不變。')}catch(e){message(e.message)}});
$('reset-weights').addEventListener('click',()=>{cfg=M.config();report=B.walkForward(data,cfg);fillWeights();render();message('已恢復預設權重。')});$('export-config').addEventListener('click',()=>download('539-'+M.configId(cfg)+'.json',{version:M.VERSION,config:cfg}));
$('data-files').addEventListener('change',async e=>{
try{
const files=[...e.target.files];if(!files.length)return;
const chunks=await Promise.all(files.map(async f=>F.parse(await f.text())));
const rows=chunks.flat().sort((a,b)=>a.period.localeCompare(b.period));
F.validate(rows);L.historyWithResults(rows,state);const computed=B.walkForward(rows,cfg);
data=rows;report=computed;page=0;syncOptions();render();
message('已載入 '+rows.length+' 期。只更新目前頁面，原TXT和已封存預測不變。');
}catch(error){message('匯入失敗：'+error.message)}finally{e.target.value=''}
});
$('export-results').addEventListener('click',()=>{const rows=filtered(),lines=[['mode','config','period','date','model','pool','hits','prediction','actual','historyCount','trainingEnd']];for(const r of rows)for(const m of M.MODELS)for(const n of B.POOLS)lines.push([mode,mode==='live'?$('live-config').value:M.configId(cfg),r.period,r.date,m.id,n,r.models[m.id].pools[n],r.models[m.id].ranking.slice(0,n).map(x=>pad(x.number)).join(' '),r.actual.map(pad).join(' '),r.historyCount,r.trainingEnd||'']);download('539-model-lab-'+mode+'.csv','\uFEFF'+lines.map(r=>r.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8')});
$('seal-form').addEventListener('submit',async e=>{e.preventDefault();if(!ready||busy)return;busy=true;renderBlind();const before=clone(state);try{const history=L.historyWithResults(data,before),next=await L.seal(before,history,$('blind-period').value,new Date($('blind-date').value).toISOString(),cfg);L.commit(localStorage,before,next);state=next;syncOptions();message('已封存A–G全排名與設定。請在開獎前匯出保留。')}catch(e){message(e.message)}finally{busy=false;render()}});
$('result-form').addEventListener('submit',async e=>{e.preventDefault();if(!ready||busy)return;busy=true;renderBlind();const before=clone(state);try{const parts=$('blind-result').value.trim().split(/[\s,，、;；]+/);if(parts.some(x=>!/^\d{1,2}$/.test(x)))throw Error('請輸入5個整數號碼。');const next=await L.score(before,parts.map(Number));L.commit(localStorage,before,next);state=next;$('blind-result').value='';syncOptions();message('答案已追加，原封存預測未修改。')}catch(e){message(e.message)}finally{busy=false;render()}});
$('export-blind').addEventListener('click',()=>download('539-model-lab-seals-'+Date.now()+'.json',state));$('export-legacy').addEventListener('click',()=>download('539-legacy-seals.json',{schema:'blind539-export-v1',records:legacyRows}));
window.addEventListener('storage',e=>{if(e.key===L.KEY||e.key===null){ready=false;renderBlind();message('其他分頁變更封存資料，請重新整理後再操作。')}});
for(const m of M.MODELS){const p=el('p');p.append(el('strong',m.id+' · '+m.name+' — '),el('span',{A:'近30期頻率；同分沿用舊版期別洗牌。',B:'遺漏期數由高到低；未出現視為截尾下限。',C:'近10期頻率與短期動能，正規化後等權。',D:'上方10項特徵依可調權重加權。',E:'与前一期號碼的近100期共現率。',F:'A–E各模型score按權重加權，不使用未來成績自動調權。',G:'固定期別偽亂數，完全不使用歷史答案。'}[m.id]));$('model-definitions').append(p)}
fillWeights();syncOptions();render();(async()=>{try{state=await L.read(localStorage);ready=true;syncOptions();render()}catch(e){message('封存儲存不可用：'+e.message+'。歷史回測仍可使用；原資料未清除。')}try{legacyRows=await L.legacy(localStorage);$('legacy-status').textContent=legacyRows.length?'保留 '+legacyRows.length+' 筆舊版預測，其中 '+legacyRows.filter(r=>r.actual!==null).length+' 筆已評分。':'此瀏覽器未找到舊版紀錄。';$('export-legacy').disabled=!legacyRows.length}catch(e){$('legacy-status').textContent=e.message+'；原資料保留。';$('export-legacy').disabled=true}})();
})();
