(function(root){
'use strict';
const node=typeof module!=='undefined'&&module.exports,F=node?require('./features.js'):root.LabFeatures,M=node?require('./models.js'):root.LabModels,B=node?require('./backtest.js'):root.LabBacktest;
const KEY='539.model-lab.v2',LEGACY_KEY='blind539.v1';
const clone=x=>JSON.parse(JSON.stringify(x)),empty=()=>({schema:'539-model-lab-v2',seals:[],results:[]});
const taipeiDate=value=>new Date(value).toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
async function hash(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)));return Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join('')}
function withoutHash(record){const {hash:unused,...value}=record;return value}
function pending(state){return state.seals.find(s=>!state.results.some(r=>r.sealHash===s.hash))}
async function verify(state){if(state?.schema!=='539-model-lab-v2'||!Array.isArray(state.seals)||!Array.isArray(state.results))throw Error('封存資料格式錯誤。');let previous='',lastPeriod='';const ids=new Set();for(const s of state.seals){if(s.version!==M.VERSION||s.previousHash!==previous||s.period<=lastPeriod||s.hash!==await hash(withoutHash(s))||!Number.isFinite(Date.parse(s.createdAt))||!Number.isFinite(Date.parse(s.drawAt))||Date.parse(s.createdAt)>=Date.parse(s.drawAt)||s.configId!==M.configId(s.config))throw Error('封存完整性檢查失敗。');F.validate(s.training);if(s.period!==String(Number(s.training.at(-1).period)+1)||s.training.some(r=>r.date>taipeiDate(s.createdAt))||s.dataHash!==await hash(s.training))throw Error('封存使用的歷史資料不合法。');const expected=M.predictions(s.training,s.period,s.config).rankings;if(JSON.stringify(expected)!==JSON.stringify(s.rankings))throw Error('封存排名與原設定不符。');ids.add(s.hash);lastPeriod=s.period;previous=s.hash}const scored=new Set();for(const r of state.results){const seal=state.seals.find(s=>s.hash===r.sealHash);if(!ids.has(r.sealHash)||scored.has(r.sealHash)||!F.validNumbers(r.actual)||!Number.isFinite(Date.parse(r.recordedAt))||Date.parse(r.recordedAt)<Date.parse(seal.drawAt)||r.hash!==await hash(withoutHash(r)))throw Error('開獎結果完整性檢查失敗。');scored.add(r.sealHash)}for(let i=0;i<state.seals.length-1;i++){const result=state.results.find(r=>r.sealHash===state.seals[i].hash);if(!result||Date.parse(result.recordedAt)>Date.parse(state.seals[i+1].createdAt))throw Error('先前期別尚未評分或封存時間順序不合法。')}return state}
async function seal(state,history,period,drawAt,settings,now=Date.now()){await verify(state);if(pending(state))throw Error('請先完成待開獎期別的評分。');F.validate(history);if(period!==String(Number(history.at(-1).period)+1)||state.seals.some(s=>s.period>=period))throw Error('請使用下一個尚未封存的連續期別。');if(!Number.isFinite(Date.parse(drawAt))||Date.parse(drawAt)<=now)throw Error('開獎時間必須晚於現在。');if(history.some(r=>r.date>taipeiDate(now)))throw Error('歷史資料含未來日期。');const prediction=M.predictions(history,period,settings);const record={version:M.VERSION,period,createdAt:new Date(now).toISOString(),drawAt:new Date(drawAt).toISOString(),config:prediction.config,configId:M.configId(prediction.config),training:clone(history),dataHash:await hash(history),rankings:prediction.rankings,nonce:Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join(''),previousHash:state.seals.at(-1)?.hash||''};record.hash=await hash(record);return {...clone(state),seals:[...clone(state.seals),record]}}
async function score(state,actual,now=Date.now()){await verify(state);const s=pending(state);if(!s)throw Error('沒有待評分預測。');if(now<Date.parse(s.drawAt))throw Error('尚未到封存的開獎時間。');if(!F.validNumbers(actual))throw Error('需要01–39的5個不重複整數。');const record={sealHash:s.hash,actual:[...actual].sort((a,b)=>a-b),recordedAt:new Date(now).toISOString()};record.hash=await hash(record);return {...clone(state),results:[...clone(state.results),record]}}
function historyWithResults(history,state){const map=new Map(history.map(r=>[r.period,r]));for(const s of state.seals){const result=state.results.find(r=>r.sealHash===s.hash);if(!result)continue;const existing=map.get(s.period);if(existing&&[...existing.numbers].sort((a,b)=>a-b).join()!==result.actual.join())throw Error('TXT答案與已封存實測答案衝突：'+s.period);map.set(s.period,{period:s.period,date:taipeiDate(s.drawAt),numbers:[...result.actual]})}return F.validate([...map.values()].sort((a,b)=>a.period.localeCompare(b.period)))}
function liveRows(state,configId){return state.seals.filter(s=>!configId||s.configId===configId).flatMap(s=>{const r=state.results.find(x=>x.sealHash===s.hash);return r?[B.evaluate({rankings:s.rankings,features:{trainingEnd:s.training.at(-1).period}},{period:s.period,date:taipeiDate(s.drawAt),numbers:r.actual},s.training.length)]:[]})}
async function read(storage){const raw=storage.getItem(KEY);return verify(raw===null?empty():JSON.parse(raw))}
function commit(storage,before,after){const current=storage.getItem(KEY);if(JSON.stringify(current===null?empty():JSON.parse(current))!==JSON.stringify(before))throw Error('其他分頁已修改紀錄，請重新整理。');storage.setItem(KEY,JSON.stringify(after))}
async function legacy(storage){const raw=storage.getItem(LEGACY_KEY);if(raw===null)return [];const rows=JSON.parse(raw);if(!Array.isArray(rows))throw Error('舊版紀錄格式錯誤。');let previous='';for(const r of rows){const payload={method:r.method,period:r.period,drawAt:r.drawAt,createdAt:r.createdAt,numbers:r.numbers,nonce:r.nonce,previousHash:r.previousHash,...(r.training?{training:r.training}:{})};if(!F.validNumbers(r.numbers)||!(r.actual===null||F.validNumbers(r.actual))||r.previousHash!==previous||r.hash!==await hash(payload))throw Error('舊版預測摘要檢查失敗。');previous=r.hash}return rows}
const api={KEY,LEGACY_KEY,hash,empty,pending,verify,seal,score,read,commit,legacy,historyWithResults,liveRows,taipeiDate};if(node)module.exports=api;else root.LabBlind=api;
})(typeof window!=='undefined'?window:globalThis);
